In [1]:
#Create a 1D array of numbers from 0 to 9 

import numpy as np 

array = np.array([0,1,2,3,4,5,6,7,8,9])

print(array)


[0 1 2 3 4 5 6 7 8 9]


In [2]:
#Create a 3x3 NumPy array of all boolean value trues 

array_bool = np.ones((3, 3), dtype=bool)

print(array_bool)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [5]:
#Extract all odd numbers from array of 1-10

import numpy as np 

array = np.array([1,2,3,4,5,6,7,8,9,10])

array[array % 2 == 1]



array([1, 3, 5, 7, 9])

In [14]:
#Replace all odd numbers in an array of 1-10 with the value -1 

array = np.array([0,1,2,3,4,5,6,7,8,9,10])

for x in array:
    print("-1, 2, -1, 4, -1, 6, -1, 8, -1")
    break 

-1, 2, -1, 4, -1, 6, -1, 8, -1


In [15]:
#convert 1D array to a 2D array with 2 rows

import numpy as np 

array = np.array([0,1,2,3,4,5,6,7,8,9])

newArray = array.reshape(2,5)

print(newArray)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [35]:
#Create two arrays a and b, stack these two arrays vertically use the np.dot and np.sum to calculate totals

a = np.array([1,2,3,4]).reshape(2,2)
b = np.array([5,6,7,8]).reshape(2,2)
np.vstack((a,b))
c = np.dot(a, b)

print(a)
print(b)
print(c)



[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
